services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5500:80"
    volumes:
      - ./Webpage:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    restart: always